/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo20.Vistas.interfaz1;

/**
 *
 * @author User
 */
public class FormDeInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDeInscripcion
     */
    public FormDeInscripcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1materiasinsc = new javax.swing.JTable();
        jbSalir3 = new javax.swing.JButton();
        jbDesincribirse = new javax.swing.JButton();
        jCInscriptoNoinscripto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jbInscribir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscripciones");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario De Inscriciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Seleccione un Alumno");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 127, 26));

        jComboBoxAlumno.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 230, -1));

        jTable1materiasinsc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1materiasinsc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1materiasinsc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1materiasinsc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 860, 190));

        jbSalir3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbSalir3.setText("Salir");
        jPanel1.add(jbSalir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 103, 37));

        jbDesincribirse.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbDesincribirse.setText("Desinscribir");
        jPanel1.add(jbDesincribirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 103, 37));

        jCInscriptoNoinscripto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inscripto", "No Inscripto" }));
        jPanel1.add(jCInscriptoNoinscripto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Materias");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, 26));

        jbInscribir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbInscribir.setText("Inscribir");
        jPanel1.add(jbInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 103, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCInscriptoNoinscripto;
    private javax.swing.JComboBox<String> jComboBoxAlumno;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1materiasinsc;
    private javax.swing.JButton jbDesincribirse;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir3;
    // End of variables declaration//GEN-END:variables
}
