/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo20.Vistas.interfaz1;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PrincipalAlumno extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalAlumno() {
        initComponents();
           this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JbSalir = new javax.swing.JButton();
        JbInscripcion = new javax.swing.JButton();
        JbMaterias = new javax.swing.JButton();
        jDesktopPaneMenuPrincipal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        JbSalir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        JbSalir.setText("Salir");
        JbSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbSalir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSalirActionPerformed(evt);
            }
        });

        JbInscripcion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        JbInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo20/Recursos/Iconos/hand_document_list_paper_file_icon_219540.png"))); // NOI18N
        JbInscripcion.setText("Inscripciones");
        JbInscripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbInscripcion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JbInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbInscripcionActionPerformed(evt);
            }
        });

        JbMaterias.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        JbMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo20/Recursos/Iconos/iconfinder-485-book-pen-food-education-4212930_114955.png"))); // NOI18N
        JbMaterias.setText("Materias");
        JbMaterias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbMaterias.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JbMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbMateriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(JbInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(JbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 130));

        jDesktopPaneMenuPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPaneMenuPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jDesktopPaneMenuPrincipalLayout = new javax.swing.GroupLayout(jDesktopPaneMenuPrincipal);
        jDesktopPaneMenuPrincipal.setLayout(jDesktopPaneMenuPrincipalLayout);
        jDesktopPaneMenuPrincipalLayout.setHorizontalGroup(
            jDesktopPaneMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneMenuPrincipalLayout.setVerticalGroup(
            jDesktopPaneMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPaneMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 540, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbInscripcionActionPerformed
       jDesktopPaneMenuPrincipal.removeAll();
        jDesktopPaneMenuPrincipal.repaint();
      InscripcionMateriaAlumno1 LisA= new InscripcionMateriaAlumno1();
        LisA.setVisible(true);
        jDesktopPaneMenuPrincipal.add(LisA);
        jDesktopPaneMenuPrincipal.moveToFront(LisA);
        
        
         Dimension desktopSize = jDesktopPaneMenuPrincipal.getSize();
        Dimension FrameSize = LisA.getSize();
        LisA.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        LisA.show();
    }//GEN-LAST:event_JbInscripcionActionPerformed

    private void JbMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbMateriasActionPerformed
      jDesktopPaneMenuPrincipal.removeAll();
        jDesktopPaneMenuPrincipal.repaint();
       MateriasInscriptasAlumno LisA= new MateriasInscriptasAlumno();
        LisA.setVisible(true);
        jDesktopPaneMenuPrincipal.add(LisA);
        jDesktopPaneMenuPrincipal.moveToFront(LisA);
        
        
         Dimension desktopSize = jDesktopPaneMenuPrincipal.getSize();
        Dimension FrameSize = LisA.getSize();
        LisA.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        LisA.show();
    }//GEN-LAST:event_JbMateriasActionPerformed

    private void JbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSalirActionPerformed
           jDesktopPaneMenuPrincipal.removeAll();
        jDesktopPaneMenuPrincipal.repaint();
        JOptionPane.showMessageDialog(this, "Saliendo");
    }//GEN-LAST:event_JbSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbInscripcion;
    private javax.swing.JButton JbMaterias;
    private javax.swing.JButton JbSalir;
    private javax.swing.JDesktopPane jDesktopPaneMenuPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
